contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # contact form url
    url(r'^contact/$', views.contact, name='contact'),
]

cwjobs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
]

cwjobsscraper/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('cwjobs.urls', namespace='cwjobs')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^users/', include('users.urls', namespace='users')),
]
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, {'document_root': settings.STATIC_ROOT})

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views
urlpatterns = [
    # Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Registration page
    url(r'^register/$', views.register, name='register'),
]

contact/models.py
from django.db import models

# Create your models here.

cwjobs/models.py
from django.db import models


class PythonJobLondon(models.Model):
    """model define the data field for the database"""
    title = models.CharField(max_length=250, null=True, blank=True)
    url = models.CharField(max_length=500, null=True, blank=True)
    date_found = models.DateTimeField(null=True, blank=True)
    date_posted = models.CharField(max_length=25, null=True, blank=True)
    salary = models.CharField(max_length=250, null=True, blank=True)
    employment_type = models.CharField(max_length=500, blank=True,null=True)

    class Meta:
        """To avoid duplicate entry in the database"""
        unique_together = ('title', 'url')

    def __unicode__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(max_length=120, required=True)
    contact_email = forms.EmailField(required=True)
    message = forms.CharField(required=True, widget=forms.Textarea)

contact/views.py
from django.conf import settings
from django.shortcuts import render
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required


from .forms import ContactForm

@login_required()
def contact(request):
    form = ContactForm(request.POST or None)
    sent = False
    if form.is_valid():
        contact_name = form.cleaned_data.get('contact_name')
        contact_email = form.cleaned_data.get('contact_email')
        message = form.cleaned_data.get('message')

        # send email message
        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email]
        contact_message = "%s: %s via %s"%(
                contact_name,
                contact_email,
                message
            )
        send_mail(subject,
                  contact_message,
                  from_email,
                  to_email,
                  fail_silently=False)
        sent = True
    context = {'form': form, 'sent': sent}

    return render(request, 'contact/contact.html', context)

cwjobs/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import PythonJobLondon


@login_required()
def index(request):
    # the home page for cwjobs scraper site
    python_jobs_london = PythonJobLondon.objects.order_by('-date_found')
    paginator = Paginator(python_jobs_london, 25) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        jobs = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver first page
        jobs = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page
        jobs = paginator.page(paginator.num_pages)

    return render(request, 'cwjobs/index.html', {'jobs': jobs})

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """log out user"""
    logout(request)
    return HttpResponseRedirect(reverse('cwjobs:index'))


def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank form
        form = UserCreationForm()
    else:
        # Process complete form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # log the user in and redirect to home page
            authenticated_user = authenticate(username=new_user.username,
                                                          password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('cwjobs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

contact/templates/contact/contact.html
{% extends 'cwjobs/base.html' %}

{% load bootstrap3 %}


{% block content %}
{% if sent %}
    <h1>Message successfully sent</h1>
    <p>Click <a href="{% url 'cwjobs:index' %}">here</a> to return to home page</p>
{% else %}
    <div class="row">
     <div class="col-md-8 col-md-offset-2 " >
        <h1>Contact Us</h1>
        <form role="form" action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit">Submit</button>
        </form>
       </div>
    </div>
{% endif %}
{% endblock %}

cwjobs/templates/cwjobs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Cwjobs webscraper</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'cwjobs:index' %}">
              Python Jobs London </a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'cwjobs:index' %}">Home</a></li>
            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
          </ul>


          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

cwjobs/templates/cwjobs/index.html
{% extends 'cwjobs/base.html' %}
{% block content %}
<h4></h4>
<div class="panel panel-default">
<div class="panel-heading text-center">Find below the list of python jobs posted on
    <a href="www.cwjobs.co.uk" target="_blank">Cwjobs</a> for London in the last 24 hours</div>
<table class="table table-bordered">
    <tr>
        <th>Job Title</th>
        <th>Employment Type</th>
        <th>Salary</th>
        <th>Date Posted</th>
        <th>Date/Time Found</th>
    </tr>
    {% for job in jobs %}
    <tr>
        <td><a rel="nofollow" target="_blank" href="{{ job.url }}">{{ job.title }}</a></td>
        <td>{{ job.employment_type }}</td>
        <td>{{ job.salary }}</td>
        <td>{{ job.date_posted }}</td>
        <td>{{ job.date_found }}</td>
    </tr>
    {% endfor %}
</table>
</div>
<div class="row">
<div class="col-md-12 text-center">
<div class="pagination" >

    <span class="step-links">
        {% if jobs.has_previous %}
            <a href="?page={{ jobs.previous_page_number }} ">previous</a>
        {% endif %}

        <span class="current">
            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
        </span>

        {% if jobs.has_next %}
            <a href="?page={{ jobs.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
    </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'cwjobs/base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row">
 <div class="col-md-4 col-md-offset-4 " >
{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-default" name="submit">Log in</button>
            <input type="hidden" name="next" value="{% url 'cwjobs:index' %}" />
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "cwjobs/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="row">
 <div class="col-md-4 col-md-offset-4 " >
  <form method="post" action="{% url 'users:register' %}">
      {% csrf_token %}

      {% bootstrap_form form %}

      <button class="btn btn-default" name="submit">Register</button>
      <input type="hidden" name="next" value="{% url 'cwjobs:index' %}" />
  </form>
   </div>
</div>
{% endblock content %}